# Import required packages

In [1]:
# Optimization Packages
using JuMP
using SCS
using GLPK

In [2]:
# Linear Algebra packages
using LinearAlgebra
using SparseArrays

In [3]:
using Pkg
Pkg.status("JuMP")

    Status `C:\Users\BV SAMEER KUMAR\Documents\JupterNotebookCodes\Julia2\Project.toml`
  [4076af6c] JuMP v0.20.1


# Part 2 Creating Model 
## Part 2.1 Creating a Model
Models are created with the `Model()` function. The `with_optimizer` syntax is used to specify the optimizer to be used:

In [4]:
model_1 = Model(with_optimizer(GLPK.Optimizer))
model_2 = Model(with_optimizer(GLPK.Optimizer))
model_3 = Model(with_optimizer(GLPK.Optimizer))
model_4 = Model(with_optimizer(GLPK.Optimizer))
model_5 = Model(with_optimizer(GLPK.Optimizer))
model_6 = Model(with_optimizer(GLPK.Optimizer));

## 2.2 Declaring some constants

In [5]:
m = 4
P1 = [[-0.7430   -0.2438   -0.6233   20.0000]; 
        [0.1724   -0.9696    0.1737  -10.0000]; 
        [-0.6467    0.0216    0.7625    2.0000]]

P2 = [[-0.9247    0.2152   -0.3140  -10.0000]; 
        [0.3105    0.9037   -0.2948   10.0000]; 
        [0.2204   -0.3701   -0.9025    3.0000]]

P3 = [[-0.6026   -0.3108   -0.7350    4.0000]; 
        [-0.5440   -0.5139    0.6633    8.0000]; 
        [-0.5839    0.7995    0.1406    1.5000]]

P4 = [[-0.6700    0.0028   -0.7424  -10.0000]; 
        [-0.6916    0.3612    0.6255    4.0000]; 
        [0.2699    0.9325   -0.2400    4.0000]]

rho = 0.1*ones(4,1)

vhat = [[9.9100   -2.7400    2.2200   -2.1200]; 
        [-5.0000    3.1400    3.6000    1.0300]];

In [6]:
# Camera 1
A1 = P1[1:2,1:3]
b1 = P1[1:2,4]
c1 = P1[3,1:3]
d1 = P1[3,4]
# Camera 2
A2 = P2[1:2,1:3]
b2 = P2[1:2,4]
c2 = P2[3,1:3]
d2 = P2[3,4]
# Camera 3
A3 = P3[1:2,1:3]
b3 = P3[1:2,4]
c3 = P3[3,1:3]
d3 = P3[3,4]
# Camera 4
A4 = P4[1:2,1:3]
b4 = P4[1:2,4]
c4 = P4[3,1:3]
d4 = P4[3,4];

## Part 2.2 Model 1
Go to the link for nice description on how to create JuMP variables [link](http://www.juliaopt.org/JuMP.jl/v0.19.0/variables/#Variables-1).

In [7]:
@variable(model_1, x[1:3])

3-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]

In [8]:
@objective(model_1, Min, x[1])

x[1]

In [9]:
# Constraints for Camera 1
@constraint(model_1, (vhat[:,1].-rho[1]/2).*(dot(c1,x)+d1) .<= A1*x + b1)
@constraint(model_1, A1*x + b1 .<= (vhat[:,1].+rho[1]/2).*(dot(c1,x) + d1))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 5.698132000000001 x[1] - 0.458936 x[2] - 8.2178 x[3] <= -0.0799999999999983             
 -3.0287650000000004 x[1] - 0.86268 x[2] + 3.9480750000000002 x[3] <= 0.09999999999999964

In [10]:
# Constraints for Camera 2
@constraint(model_1, (vhat[:,2].-rho[2]/2).*(dot(c2,x)+d2) .<= A2*x + b2)
@constraint(model_1, A2*x + b2 .<= (vhat[:,2].+rho[2]/2).*(dot(c2,x) + d2))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.3318239999999999 x[1] - 0.7803690000000001 x[2] - 2.741725 x[3] <= 1.9299999999999997
 -0.39257600000000004 x[1] + 2.084319 x[2] + 2.584175 x[3] <= -0.4299999999999997        

In [11]:
# Constraints for Camera 3
@constraint(model_1, (vhat[:,3].-rho[3]/2).*(dot(c3,x)+d3) .<= A3*x + b3)
@constraint(model_1, A3*x + b3 .<= (vhat[:,3].+rho[3]/2).*(dot(c3,x) + d3))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 0.722853 x[1] - 2.125665 x[2] - 1.054162 x[3] <= -0.5949999999999998                               
 1.5872349999999997 x[1] - 3.4320749999999998 x[2] + 0.15010999999999997 x[3] <= -2.5250000000000004

In [12]:
# Constraints for Camera 4
@constraint(model_1, (vhat[:,4].-rho[4]/2).*(dot(c4,x)+d4) .<= A4*x + b4)
@constraint(model_1, A4*x + b4 .<= (vhat[:,4].+rho[4]/2).*(dot(c4,x) + d4))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.11130700000000004 x[1] + 1.933075 x[2] - 1.2392 x[3] <= 1.7199999999999989           
 -0.983092 x[1] - 0.6459000000000001 x[2] + 0.8846999999999999 x[3] <= 0.3200000000000003

In [13]:
println("Starting to optimize Model 1.....")
optimize!(model_1)
println("Termation Status of the model: ", termination_status(model_1))

Starting to optimize Model 1.....
Termation Status of the model: OPTIMAL


In [14]:
println("Max value of objective function: ", objective_value(model_1))
println("Value of the variable x: ", value.(x))
println("Hence value of l1 is ", value.(x[1]))

Max value of objective function: -0.9956131400879996
Value of the variable x: [-0.9956131400879996, 0.3110104348932551, -0.6719618369714886]
Hence value of l1 is -0.9956131400879996


## Part 2.3 Model 2

In [15]:
@variable(model_2, x[1:3])

3-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]

In [16]:
@objective(model_2, Max, x[1])

x[1]

In [17]:
# Constraints for Camera 1
@constraint(model_2, (vhat[:,1].-rho[1]/2).*(dot(c1,x)+d1) .<= A1*x + b1)
@constraint(model_2, A1*x + b1 .<= (vhat[:,1].+rho[1]/2).*(dot(c1,x) + d1))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 5.698132000000001 x[1] - 0.458936 x[2] - 8.2178 x[3] <= -0.0799999999999983             
 -3.0287650000000004 x[1] - 0.86268 x[2] + 3.9480750000000002 x[3] <= 0.09999999999999964

In [18]:
# Constraints for Camera 2
@constraint(model_2, (vhat[:,2].-rho[2]/2).*(dot(c2,x)+d2) .<= A2*x + b2)
@constraint(model_2, A2*x + b2 .<= (vhat[:,2].+rho[2]/2).*(dot(c2,x) + d2))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.3318239999999999 x[1] - 0.7803690000000001 x[2] - 2.741725 x[3] <= 1.9299999999999997
 -0.39257600000000004 x[1] + 2.084319 x[2] + 2.584175 x[3] <= -0.4299999999999997        

In [19]:
# Constraints for Camera 3
@constraint(model_2, (vhat[:,3].-rho[3]/2).*(dot(c3,x)+d3) .<= A3*x + b3)
@constraint(model_2, A3*x + b3 .<= (vhat[:,3].+rho[3]/2).*(dot(c3,x) + d3))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 0.722853 x[1] - 2.125665 x[2] - 1.054162 x[3] <= -0.5949999999999998                               
 1.5872349999999997 x[1] - 3.4320749999999998 x[2] + 0.15010999999999997 x[3] <= -2.5250000000000004

In [20]:
# Constraints for Camera 4
@constraint(model_2, (vhat[:,4].-rho[4]/2).*(dot(c4,x)+d4) .<= A4*x + b4)
@constraint(model_2, A4*x + b4 .<= (vhat[:,4].+rho[4]/2).*(dot(c4,x) + d4))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.11130700000000004 x[1] + 1.933075 x[2] - 1.2392 x[3] <= 1.7199999999999989           
 -0.983092 x[1] - 0.6459000000000001 x[2] + 0.8846999999999999 x[3] <= 0.3200000000000003

In [21]:
println("Starting to optimize Model 2.....")
optimize!(model_2)
println("Termation Status of the model: ", termination_status(model_2))

Starting to optimize Model 2.....
Termation Status of the model: OPTIMAL


In [22]:
println("Max value of objective function: ", objective_value(model_2))
println("Value of the variable x: ", value.(x))
println("Hence value of u1 is ", value.(x[1]))

Max value of objective function: -0.8245037492559099
Value of the variable x: [-0.8245037492559099, 0.3290148883401633, -0.5803412074460756]
Hence value of u1 is -0.8245037492559099


## Part 2.4 Model 3

In [23]:
@variable(model_3, x[1:3])

3-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]

In [24]:
@objective(model_3, Min, x[2])

x[2]

In [25]:
# Constraints for Camera 1
@constraint(model_3, (vhat[:,1].-rho[1]/2).*(dot(c1,x)+d1) .<= A1*x + b1)
@constraint(model_3, A1*x + b1 .<= (vhat[:,1].+rho[1]/2).*(dot(c1,x) + d1))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 5.698132000000001 x[1] - 0.458936 x[2] - 8.2178 x[3] <= -0.0799999999999983             
 -3.0287650000000004 x[1] - 0.86268 x[2] + 3.9480750000000002 x[3] <= 0.09999999999999964

In [26]:
# Constraints for Camera 2
@constraint(model_3, (vhat[:,2].-rho[2]/2).*(dot(c2,x)+d2) .<= A2*x + b2)
@constraint(model_3, A2*x + b2 .<= (vhat[:,2].+rho[2]/2).*(dot(c2,x) + d2))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.3318239999999999 x[1] - 0.7803690000000001 x[2] - 2.741725 x[3] <= 1.9299999999999997
 -0.39257600000000004 x[1] + 2.084319 x[2] + 2.584175 x[3] <= -0.4299999999999997        

In [27]:
# Constraints for Camera 3
@constraint(model_3, (vhat[:,3].-rho[3]/2).*(dot(c3,x)+d3) .<= A3*x + b3)
@constraint(model_3, A3*x + b3 .<= (vhat[:,3].+rho[3]/2).*(dot(c3,x) + d3))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 0.722853 x[1] - 2.125665 x[2] - 1.054162 x[3] <= -0.5949999999999998                               
 1.5872349999999997 x[1] - 3.4320749999999998 x[2] + 0.15010999999999997 x[3] <= -2.5250000000000004

In [28]:
# Constraints for Camera 4
@constraint(model_3, (vhat[:,4].-rho[4]/2).*(dot(c4,x)+d4) .<= A4*x + b4)
@constraint(model_3, A4*x + b4 .<= (vhat[:,4].+rho[4]/2).*(dot(c4,x) + d4))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.11130700000000004 x[1] + 1.933075 x[2] - 1.2392 x[3] <= 1.7199999999999989           
 -0.983092 x[1] - 0.6459000000000001 x[2] + 0.8846999999999999 x[3] <= 0.3200000000000003

In [29]:
println("Starting to optimize Model 3.....")
optimize!(model_3)
println("Termation Status of the model: ", termination_status(model_3))

Starting to optimize Model 3.....
Termation Status of the model: OPTIMAL


In [30]:
println("Max value of objective function: ", objective_value(model_3))
println("Value of the variable x: ", value.(x))
println("Hence value of l2 is ", value.(x[2]))

Max value of objective function: 0.27530820527613903
Value of the variable x: [-0.9357151240275203, 0.27530820527613903, -0.6323482545538253]
Hence value of l2 is 0.27530820527613903


## Part 2.5 Model 4

In [31]:
@variable(model_4, x[1:3])

3-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]

In [32]:
@objective(model_4, Max, x[2])

x[2]

In [33]:
# Constraints for Camera 1
@constraint(model_4, (vhat[:,1].-rho[1]/2).*(dot(c1,x)+d1) .<= A1*x + b1)
@constraint(model_4, A1*x + b1 .<= (vhat[:,1].+rho[1]/2).*(dot(c1,x) + d1))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 5.698132000000001 x[1] - 0.458936 x[2] - 8.2178 x[3] <= -0.0799999999999983             
 -3.0287650000000004 x[1] - 0.86268 x[2] + 3.9480750000000002 x[3] <= 0.09999999999999964

In [34]:
# Constraints for Camera 2
@constraint(model_4, (vhat[:,2].-rho[2]/2).*(dot(c2,x)+d2) .<= A2*x + b2)
@constraint(model_4, A2*x + b2 .<= (vhat[:,2].+rho[2]/2).*(dot(c2,x) + d2))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.3318239999999999 x[1] - 0.7803690000000001 x[2] - 2.741725 x[3] <= 1.9299999999999997
 -0.39257600000000004 x[1] + 2.084319 x[2] + 2.584175 x[3] <= -0.4299999999999997        

In [35]:
# Constraints for Camera 3
@constraint(model_4, (vhat[:,3].-rho[3]/2).*(dot(c3,x)+d3) .<= A3*x + b3)
@constraint(model_4, A3*x + b3 .<= (vhat[:,3].+rho[3]/2).*(dot(c3,x) + d3))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 0.722853 x[1] - 2.125665 x[2] - 1.054162 x[3] <= -0.5949999999999998                               
 1.5872349999999997 x[1] - 3.4320749999999998 x[2] + 0.15010999999999997 x[3] <= -2.5250000000000004

In [36]:
# Constraints for Camera 4
@constraint(model_4, (vhat[:,4].-rho[4]/2).*(dot(c4,x)+d4) .<= A4*x + b4)
@constraint(model_4, A4*x + b4 .<= (vhat[:,4].+rho[4]/2).*(dot(c4,x) + d4))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.11130700000000004 x[1] + 1.933075 x[2] - 1.2392 x[3] <= 1.7199999999999989           
 -0.983092 x[1] - 0.6459000000000001 x[2] + 0.8846999999999999 x[3] <= 0.3200000000000003

In [37]:
println("Starting to optimize Model 4.....")
optimize!(model_4)
println("Termation Status of the model: ", termination_status(model_4))

Starting to optimize Model 4.....
Termation Status of the model: OPTIMAL


In [38]:
println("Max value of objective function: ", objective_value(model_4))
println("Value of the variable x: ", value.(x))
println("Hence value of u2 is ", value.(x[2]))

Max value of objective function: 0.37836925050189607
Value of the variable x: [-0.8554851028610982, 0.37836925050189607, -0.6015401966111659]
Hence value of u2 is 0.37836925050189607


## Part 2.6 Model 5

In [39]:
@variable(model_5, x[1:3])

3-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]

In [40]:
@objective(model_5, Min, x[3])

x[3]

In [41]:
# Constraints for Camera 1
@constraint(model_5, (vhat[:,1].-rho[1]/2).*(dot(c1,x)+d1) .<= A1*x + b1)
@constraint(model_5, A1*x + b1 .<= (vhat[:,1].+rho[1]/2).*(dot(c1,x) + d1))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 5.698132000000001 x[1] - 0.458936 x[2] - 8.2178 x[3] <= -0.0799999999999983             
 -3.0287650000000004 x[1] - 0.86268 x[2] + 3.9480750000000002 x[3] <= 0.09999999999999964

In [42]:
# Constraints for Camera 2
@constraint(model_5, (vhat[:,2].-rho[2]/2).*(dot(c2,x)+d2) .<= A2*x + b2)
@constraint(model_5, A2*x + b2 .<= (vhat[:,2].+rho[2]/2).*(dot(c2,x) + d2))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.3318239999999999 x[1] - 0.7803690000000001 x[2] - 2.741725 x[3] <= 1.9299999999999997
 -0.39257600000000004 x[1] + 2.084319 x[2] + 2.584175 x[3] <= -0.4299999999999997        

In [43]:
# Constraints for Camera 3
@constraint(model_5, (vhat[:,3].-rho[3]/2).*(dot(c3,x)+d3) .<= A3*x + b3)
@constraint(model_5, A3*x + b3 .<= (vhat[:,3].+rho[3]/2).*(dot(c3,x) + d3))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 0.722853 x[1] - 2.125665 x[2] - 1.054162 x[3] <= -0.5949999999999998                               
 1.5872349999999997 x[1] - 3.4320749999999998 x[2] + 0.15010999999999997 x[3] <= -2.5250000000000004

In [44]:
# Constraints for Camera 4
@constraint(model_5, (vhat[:,4].-rho[4]/2).*(dot(c4,x)+d4) .<= A4*x + b4)
@constraint(model_5, A4*x + b4 .<= (vhat[:,4].+rho[4]/2).*(dot(c4,x) + d4))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.11130700000000004 x[1] + 1.933075 x[2] - 1.2392 x[3] <= 1.7199999999999989           
 -0.983092 x[1] - 0.6459000000000001 x[2] + 0.8846999999999999 x[3] <= 0.3200000000000003

In [45]:
println("Starting to optimize Model 5.....")
optimize!(model_5)
println("Termation Status of the model: ", termination_status(model_5))

Starting to optimize Model 5.....
Termation Status of the model: OPTIMAL


In [46]:
println("Max value of objective function: ", objective_value(model_5))
println("Value of the variable x: ", value.(x))
println("Hence value of l3 is ", value.(x[3]))

Max value of objective function: -0.6789891850297552
Value of the variable x: [-0.9672074497243972, 0.32362160480882063, -0.6789891850297552]
Hence value of l3 is -0.6789891850297552


## Part 2.7 Model 6

In [47]:
@variable(model_6, x[1:3])

3-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]

In [48]:
@objective(model_6, Max, x[3])

x[3]

In [49]:
# Constraints for Camera 1
@constraint(model_6, (vhat[:,1].-rho[1]/2).*(dot(c1,x)+d1) .<= A1*x + b1)
@constraint(model_6, A1*x + b1 .<= (vhat[:,1].+rho[1]/2).*(dot(c1,x) + d1))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 5.698132000000001 x[1] - 0.458936 x[2] - 8.2178 x[3] <= -0.0799999999999983             
 -3.0287650000000004 x[1] - 0.86268 x[2] + 3.9480750000000002 x[3] <= 0.09999999999999964

In [50]:
# Constraints for Camera 2
@constraint(model_6, (vhat[:,2].-rho[2]/2).*(dot(c2,x)+d2) .<= A2*x + b2)
@constraint(model_6, A2*x + b2 .<= (vhat[:,2].+rho[2]/2).*(dot(c2,x) + d2))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.3318239999999999 x[1] - 0.7803690000000001 x[2] - 2.741725 x[3] <= 1.9299999999999997
 -0.39257600000000004 x[1] + 2.084319 x[2] + 2.584175 x[3] <= -0.4299999999999997        

In [51]:
# Constraints for Camera 3
@constraint(model_6, (vhat[:,3].-rho[3]/2).*(dot(c3,x)+d3) .<= A3*x + b3)
@constraint(model_6, A3*x + b3 .<= (vhat[:,3].+rho[3]/2).*(dot(c3,x) + d3))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 0.722853 x[1] - 2.125665 x[2] - 1.054162 x[3] <= -0.5949999999999998                               
 1.5872349999999997 x[1] - 3.4320749999999998 x[2] + 0.15010999999999997 x[3] <= -2.5250000000000004

In [52]:
# Constraints for Camera 4
@constraint(model_6, (vhat[:,4].-rho[4]/2).*(dot(c4,x)+d4) .<= A4*x + b4)
@constraint(model_6, A4*x + b4 .<= (vhat[:,4].+rho[4]/2).*(dot(c4,x) + d4))

2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}},ScalarShape},1}:
 -0.11130700000000004 x[1] + 1.933075 x[2] - 1.2392 x[3] <= 1.7199999999999989           
 -0.983092 x[1] - 0.6459000000000001 x[2] + 0.8846999999999999 x[3] <= 0.3200000000000003

In [53]:
println("Starting to optimize Model 6.....")
optimize!(model_6)
println("Termation Status of the model: ", termination_status(model_6))

Starting to optimize Model 6.....
Termation Status of the model: OPTIMAL


In [54]:
println("Max value of objective function: ", objective_value(model_6))
println("Value of the variable x: ", value.(x))
println("Hence value of u3 is ", value.(x[3]))

Max value of objective function: -0.5735233124623511
Value of the variable x: [-0.852930477369706, 0.31616654919206966, -0.5735233124623511]
Hence value of u3 is -0.5735233124623511
